#!/bin/bash

# Make a request for a pokeman.
URL="https://pokeapi.co/api/v2/pokemon/"
RES=$(curl -s "$URL")

# Check if the request was successfull
if [ -n "$RES" ]; then
    echo "Request is successfull."
    echo "$RES" >> "data.json"
else
    echo "Error."
    cat "Error" >> "errors.txt"
fi